print('Olá, mundo!')
print('Este é meu texto')
print('my aunt used to live in paris')
print('she jumped into the river, once, barefoot')
print('-i love you.')
print('itll pass...')
print('anyway, thats the very reason why they put rubbers on the end of pencils.')
print('to fuck hamsters?!')
print('No, because people make mistakes...')
